import { CategoryRaw } from './category.raw';

export const categoryStagingSample: CategoryRaw = {
  "0": "Array Helpers",
  "1": "Position Prices",
  "2": "Charting",
  "3": "Custom Commands",
  "4": "Custom Commands Helpers",
  "5": "Enumerations Trading LR",
  "6": "Enumerations Color",
  "7": "Enumerations Charting",
  "8": "Enumerations Moving Averages",
  "9": "Enumerations Position",
  "10": "Enumerations Parameter Type",
  "11": "Enumerations Signal",
  "12": "Enumerations Trading",
  "13": "Enumerations Order Types",
  "14": "Easy Safeties",
  "15": "Easy Insurances",
  "16": "Easy Indicators",
  "17": "Equations",
  "18": "Input Fields",
  "19": "Input Settings",
  "20": "Trade Actions (Managed)",
  "21": "Mathematical",
  "22": "Memory Helpers",
  "23": "Miscellaneous",
  "24": "Position Information",
  "25": "Order Handling",
  "26": "Order Information",
  "27": "Price Data",
  "28": "Price Market Information",
  "29": "Profit Information",
  "30": "Settings",
  "31": "Signal Helpers",
  "32": "String Helpers",
  "33": "Technical Analysis",
  "34": "Technical Analysis Helpers",
  "35": "Time Information",
  "36": "Trade Bot",
  "37": "Trade Market Information",
  "38": "Trade Actions (Unmanaged)",
  "39": "Wallet",
  "40": "Flow Control",
  "41": "Enumerations Candle Pattern",
  "42": "Enumerations Signal Types",
  "43": "Enumerations Data Types",
  "44": "Enumerations Array filter Types",
  "45": "Social Media",
  "46": "Enumerations Source Price Types"
};
